title: Saleem Kamaludin
description: Researcher & Lecturer • Discrete Mathematics • Graph theory
theme: minima

permalink: pretty


# Use minima’s built‑in dark mode
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/SaleemKamaludin" }
    # add more if you like:
    # - { platform: email,   user_url: "mailto:your.email@uwi.edu" }
    # - { platform: linkedin, user_url: "https://www.linkedin.com/in/your-handle" }

# Show these pages in the top nav (order matters)
header_pages:
  - index.md
  - research.md
  - teaching.md
  - courses.md
  - courses/math-for-business.md
  - links.md
  - courses/math-1115/index.md


# MathJax for LaTeX
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
