name: Update site screenshot

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - main  # also run on pushes to main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Take screenshot with xvfb
        run: |
          npx xvfb-run --auto-servernum node scripts/screenshot.mjs

      - name: Commit screenshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update site screenshot"
          file_pattern: screenshot*.png
